fragment task on Task {
  uuid
  content
  state
  source
  created_at
  updated_at
  user {
    ...user
  }
  images {
    uuid
    url
    thumbnail_url
  }
  comments {
    nodes {
      uuid
    }
  }
  likes {
    nodes {
      uuid
      user {
        uuid
      }
    }
  }
}
