query GetAllLikes ($taskUuid: String!) {
  all_likes (taskUuid: $taskUuid) {
    nodes {
      uuid
      created_at
      user {
        uuid
        username
        first_name
        last_name
        streak
        avatar_url
      }
    }
  }
}
