query GetAllLinks ($cursor: String) {
  allLinks (after: $cursor) {
    nodes {
      uuid
      title
      url
      createdAt
      user {
        uuid
        username
        firstName
        lastName
        avatarUrl
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
