query GetAllLinks ($cursor: String) {
  all_links (after: $cursor) {
    nodes {
      uuid
      title
      url
      created_at
      user {
        uuid
        username
        first_name
        last_name
        avatar_url
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
