require: rubocop-rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 35

Metrics/AbcSize:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
