name: Deployment

on:
  push:
    branches: master

jobs:
  deploy:
    name: Deploy to Kubernetes cluster
    runs-on: ubuntu-latest
    env:
      KUBECONFIG: ~/kubeconfig.yaml

    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Dockerhub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Install Devspace
      run: curl -s -L "https://github.com/loft-sh/devspace/releases/tag/v5.14.0" | sed -nE 's!.*"([^"]*devspace-linux-amd64)".*!https://github.com\1!p' | xargs -n 1 curl -L -o devspace && chmod +x devspace && sudo install devspace /usr/local/bin

    - uses: azure/k8s-set-context@v1
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}

    - name: Deploy
      run: devspace deploy --namespace checkmark --force-build
